# Generated by Django 4.2.5 on 2023-09-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('model', models.CharField(max_length=2)),
                ('version', models.CharField(max_length=2)),
            ],
        ),
    ]
